### ISSUE TITLE
はてなスペースについて

### ISSUE THREAD

**Issue by 844196** [vill-osamu/issues#1]
ちょうど1年前、「おさむ村情報共有円滑化社会実験」の一環として設置した[おさむ村 はてなスペース](http://space.hatena.ne.jp/~/14290001378108994803)ですが、特に利用されることもなく放置されています。

現在は[おさむ村 いろんなまとめ](http://vill-osamu.github.io)もあり、同種のサイトが存在するのは紛らわしいので、特に存続や廃止に関して意見がなければ、この投稿から48時間以内にスペースを削除したいと思います。

**Comment by OsamuMORIMOTO** [comment]
お前・・・消えるのか？

**Comment by 844196** [comment]
期限を過ぎましたので事前の通告通り、はてなスペースを削除します

**Comment by 844196** [comment]
![hatena space 2015-02-08 05-29-49](https://cloud.githubusercontent.com/assets/4990822/6093819/84996304-af53-11e4-906e-587e58a5c1ba.png)

削除しました
