### ISSUE TITLE
沢田研二のインストラクターおよび具の消失について

### ISSUE THREAD

**Issue by keepoff07** [vill-osamu/issues#18]
`沢田研二のインストラクター`および`具`が消失したことを報告します。

> 具が消えてるんだけど
> ![2015-11-06-04_25](https://pbs.twimg.com/media/CTEjvTyVEAAsUD9.png)
> [@keep_off07](https://twitter.com/keep_off07) [4:25 - 2015年11月6日](https://twitter.com/keep_off07/status/662349917323530240)

　

> ここ空き家でしたっけ
> ![2015-11-06-04_32](https://pbs.twimg.com/media/CTElgQVUkAAyGg1.png)
> [@keep_off07](https://twitter.com/keep_off07) [4:32 - 2015年11月6日](https://twitter.com/keep_off07/status/662351857843482624)
## 現状

上記の通りです。
具に関しては11月1日(日曜)には消失していなかったのを確認しております。

> ![nico](https://pbs.twimg.com/media/CTEn7PgU8AAcq8S.png)
> [ｱﾄﾞﾍﾞﾝﾄｶﾚﾝﾀﾞｰ - 2015/11/01 23:34開始 - ニコニコ生放送](http://live.nicovideo.jp/watch/lv240540531#29:10)

また、具と一緒の柵内に居た黒ウサギも、安否の確認が難しい為消息不明となっております。
## 事案発生から起票時点までに行われた措置

> [@keep_off07](https://twitter.com/keep_off07) 本件、状況確認しました。XRay及びエンティティレーダで周囲150ブロックを走査しましたが、発見できませんでした。一次報告者としてチケットを切ってもらえるとうれしいです。
> [@844196](https://twitter.com/844196) [12:03 - 2015年11月6日](https://twitter.com/844196/status/662465353637728256)
## 村民に対する注意事項

ありません

**Comment by 844196** [comment]
@keepoff07 THX. :sushi: 

@OsamuMORIMOTO 

本件に関連すると思われる、住居及び構造物の損壊はありません。
荒らしではないとは思いますが、最終確認時点である2015-11-01から2015-11-06までのログを確認してください。

**Comment by 844196** [comment]
本件は以下の理由により、クローズとします。
1. ログを解析した結果、2015-11-01から2015-11-06の間にログインしたユーザは以下の通り
   - keep_off07
   - MiyauchiRenge
   - 844196
   - hyousikinuko
2. `1`以外のユーザがログインした形跡もなく、また、異常終了等があった事実は確認できず
3. よって本件は、偶発的かつ再現性のない不幸な事故であったと言わざるをえない

---

![cmd-chan](http://i.imgur.com/8hZAXXT.png)
