### ISSUE TITLE
1.8サーバー 導入プラグインについて

### ISSUE THREAD

**Issue by 844196** [vill-osamu/issues#4]
#2 より分割

**Comment by 844196** [comment]
@OsamuMORIMOTO は現在1.7環境で使っているプラグインのリストを列挙していってください

**Comment by 844196** [comment]
@OsamuMORIMOTO 
プラグインをここから増やしたり、逆に減らしていくとか考えはあります？

**Comment by OsamuMORIMOTO** [comment]
@844196 
現時点で運用している"おさむ村サーバ"のbukkitプラグインは以下のものを使用しております。
- AutoSaveWorld
- ChatManager
- dynmap-1.9.3
- Modifyworld
- PermissionsEx
- WorldEdit

また、以前のヴァージョンで導入していたプラグインを以下に列挙いたします。
- ShadowAdmin

**Comment by OsamuMORIMOTO** [comment]
@844196 
プラグインの追加、削減は必要と考えております。
以下の観点に関係するものを洗い出して、調査いたします。
- サーバの機能に同等のものが備わっていることも考えられるプラグイン
  - サーバに現状使用しているプラグインと同等の機能があるか
  - サーバの機能で十分であるか
  - ex. AutoSaveWorld, PermissionsEx
- 慣習で導入しているプラグイン
  - 現在では必要なものなのか
  - 現在の主流として必要か
  - ex. ChatManager, Modifyworld
- 上記項目とかぶるところもあるが、現在の主流にそったプラグイン
  - 似たプラグインで新しい物が存在するか
  - 評判や機能がよければ、最新のものを導入していいきたい

**Comment by 844196** [comment]
@OsamuMORIMOTO 

> プラグインの追加、削減は必要と考えております。
> 以下の観点に関係するものを洗い出して、調査いたします。

ざっと見た感じ、現在使用している主に管理機能向けプラグイン関係のみ導入予定で、それ以外の例えば「PvP支援プラグイン」や「椅子に座れるプラグイン」、「貨幣経済プラグイン」なんかは特段の要望がない限り予定していない。という認識であってますか？

**Comment by OsamuMORIMOTO** [comment]
@844196 

> ざっと見た感じ、現在使用している主に管理機能向けプラグイン関係のみ導入予定で、それ以外の例えば「PvP支援プラグイン」や「椅子に座れるプラグイン」、「貨幣経済プラグイン」なんかは特段の要望がない限り予定していない。という認識であってますか？

その認識であっております。
今までどおりできる限りバニラで進めていくことを考えております。

**Comment by 844196** [comment]
# ひげさんに聞いたやつ 1/2

## お遊び系
- レシピ追加
  - いらなさそう
- スキル
  - バランス壊れる
  - グローストーンが土掘るだけで取れるとか（らしい）

## 管理系のトレンド
- HawkEye
  - ログとれるやつ
  - 前入れてたやつ？
  - `shadow admin`と内容がかぶっている
  - SQL鯖立ててログはDBにアクセスしてみるらしい（Minecraftゲーム画面からも観れる）
    - `shadow admin`はテキストに出力される（だけ？）らしい

**Comment by 844196** [comment]
# ひげさんに聞いたやつ 2/2
- スーパーメンバー構想
  - 仕事ないしいらなくね？

**Comment by 844196** [comment]
> **当面`Dynmap`のみで運用**
> 権限はホワイトリストで代用

**Comment by 844196** [comment]
一旦Close
