### ISSUE TITLE
1.8サーバー　Spigot稼動試験

### ISSUE THREAD

**Issue by OsamuMORIMOTO** [vill-osamu/issues#7]
現在上がっているissuesの進捗確認として実施しようと思います。

　日時：4月11日(土)　昼ごろ予定

また、各isuueには期限などが設けられていないので、
この試験に向けての進捗目標を設定いたします。

TODO
- 各isuueに、この試験に向けての進捗目標を設定する。
- 稼動試験で実施する作業をあげる

**Comment by 844196** [comment]
内容を確認しましたが、「Spigot稼動試験」でマイルストーンを切り、各トピックチケットをそれに紐付けようと思います。このissueはcloseしますが、上記内容を引用で貼り付けます。

**Comment by 844196** [comment]
## 補遺1

現在、この稼働試験は████████の████により停止されています。
再開された場合はこのチケットを████してください。

### 文書 #7-ログ1

```
[22時02分50秒] ████: あ、そうだ(唐突
[22時02分58秒] ████: █はちゃんと生きてるんですかね？
[22時03分40秒] はちよん: 今pingを打っておきました
```

### 文書 #7-ログ2

```
[22時03分21秒] はちよん: $ ping
[23時37分09秒] █████: タイムアウトしました
```
